apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# bases:
#   - 'github.com/vitus133/ran-profiles/du/sriov?ref=dev'

resources:
  - 04-sriov-networknodepolicy.yaml
  - 05-sriov-network.yaml
