apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: sriov-nnp-du-ldc-numa0-mh
  namespace: openshift-sriov-network-operator
spec:
# This works for Intel based NICs.
# For Mellanox please change to:
#     deviceType: netdevice
#     isRdma: true
  deviceType: vfio-pci
  isRdma: false
  nicSelector:
# The exact physical function name must match the hardware used    
    pfNames: ["ens7f1"]
  nodeSelector:
    node-role.kubernetes.io/worker-du-ldc: ""
  numVfs: 2
  priority: 10
  resourceName: du_ldc_mh_n0
