apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: container-mount-ns-service
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf8;base64,W1VuaXRdCkRlc2NyaXB0aW9uPU1hbmFnZXMgYSBtb3VudCBuYW1lc3BhY2UgdGhhdCBib3RoIGt1YmVsZXQgYW5kIGNyaW8gY2FuIHVzZSB0byBzaGFyZSB0aGVpciBjb250YWluZXItc3BlY2lmaWMgbW91bnRzCgpbU2VydmljZV0KUHJpdmF0ZU1vdW50cz1vbgpFeGVjU3RhcnQ9YmFzaCAtYyAnd2hpbGUgOjsgZG8gc2xlZXAgaW5maW5pdHk7IGRvbmUnCgo=
        filesystem: root
        mode: 420
        path: /etc/systemd/system/container-mount-namespace.service
