apiVersion: performance.openshift.io/v1alpha1
kind: PerformanceProfile
metadata:
  name: performance
spec:
  cpu:
    isolated: "5,7,9"
    reserved: "0-4,6,8,10-103"
  hugepages:
    defaultHugepagesSize: 1G
    pages: 
    - size: "1G"
      count: 10
      node: 1
  nodeSelector:
    node-role.kubernetes.io/worker-cnf: ""
  numa:
    topologyPolicy: best-effort
  realTimeKernel:
    enabled: false
