apiVersion: performance.openshift.io/v1
kind: PerformanceProfile
metadata:
  name: perf-example-du-fec
spec:
  additionalKernelArgs:
  - nosmt
  cpu:
    # Temp. workaround for RT kernel bugs that consume too much 
    # CPU power: add more isolated cores
    isolated: "1,3,5,7,9-51"
    reserved: "0,2,4,6,8"
  hugepages:
    defaultHugepagesSize: 1G
    pages:
    - count: 16
      size: 1G
      node: 0
