apiVersion: performance.openshift.io/v1
kind: PerformanceProfile
metadata:
  name: performance
spec:
  nodeSelector:
    node-role.kubernetes.io/worker-cnf: ""
  cpu:
  #   # PowerEdge R640, 2xIntel(R) Xeon(R) Gold 6230R CPU @ 2.10GHz
  #   # On-line CPU(s) list:  0-51
  #   # Off-line CPU(s) list: 52-103
  #   # NUMA node0 CPU(s):    0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50
  #   # NUMA node1 CPU(s):    1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51
    reserved: "0,2"  
    isolated: "1,3-51"
  realTimeKernel:
    enabled: true
  numa:
    topologyPolicy: "restricted"
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
    - size: "1G"
      count: 8
      node: 0    
  additionalKernelArgs:
    - nmi_watchdog=0
    - audit=0
    - mce=off
    - processor.max_cstate=1
    - idle=poll
    - intel_idle.max_cstate=0
    - nosmt
    - tsc=reliable
